

    FUNCTION Assert_Equal_INT
            VAR_INPUT
		         expected:  INT;
		         actual:  INT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_Equal_SINT
            VAR_INPUT
		         expected:  SINT;
		         actual:  SINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_Equal_DINT
            VAR_INPUT
		         expected:  DINT;
		         actual:  DINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_Equal_LINT
            VAR_INPUT
		         expected:  LINT;
		         actual:  LINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_Equal_USINT
            VAR_INPUT
		         expected:  USINT;
		         actual:  USINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_Equal_UINT
            VAR_INPUT
		         expected:  UINT;
		         actual:  UINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_Equal_UDINT
            VAR_INPUT
		         expected:  UDINT;
		         actual:  UDINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_Equal_ULINT
            VAR_INPUT
		         expected:  ULINT;
		         actual:  ULINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_Equal_REAL
            VAR_INPUT
		         expected:  REAL;
		         actual:  REAL;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_Equal_LREAL
            VAR_INPUT
		         expected:  LREAL;
		         actual:  LREAL;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_Equal_BOOL
            VAR_INPUT
		         expected:  BOOL;
		         actual:  BOOL;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_NotEqual_INT
            VAR_INPUT
		         expected:  INT;
		         actual:  INT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_NotEqual_SINT
            VAR_INPUT
		         expected:  SINT;
		         actual:  SINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_NotEqual_DINT
            VAR_INPUT
		         expected:  DINT;
		         actual:  DINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_NotEqual_LINT
            VAR_INPUT
		         expected:  LINT;
		         actual:  LINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_NotEqual_USINT
            VAR_INPUT
		         expected:  USINT;
		         actual:  USINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_NotEqual_UINT
            VAR_INPUT
		         expected:  UINT;
		         actual:  UINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_NotEqual_UDINT
            VAR_INPUT
		         expected:  UDINT;
		         actual:  UDINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_NotEqual_ULINT
            VAR_INPUT
		         expected:  ULINT;
		         actual:  ULINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_NotEqual_REAL
            VAR_INPUT
		         expected:  REAL;
		         actual:  REAL;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_NotEqual_LREAL
            VAR_INPUT
		         expected:  LREAL;
		         actual:  LREAL;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_NotEqual_BOOL
            VAR_INPUT
		         expected:  BOOL;
		         actual:  BOOL;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_GreaterThan_INT
            VAR_INPUT
		         left:  INT;
		         right:  INT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_GreaterThan_SINT
            VAR_INPUT
		         left:  SINT;
		         right:  SINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_GreaterThan_DINT
            VAR_INPUT
		         left:  DINT;
		         right:  DINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_GreaterThan_LINT
            VAR_INPUT
		         left:  LINT;
		         right:  LINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_GreaterThan_USINT
            VAR_INPUT
		         left:  USINT;
		         right:  USINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_GreaterThan_UINT
            VAR_INPUT
		         left:  UINT;
		         right:  UINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_GreaterThan_UDINT
            VAR_INPUT
		         left:  UDINT;
		         right:  UDINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_GreaterThan_ULINT
            VAR_INPUT
		         left:  ULINT;
		         right:  ULINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_GreaterThan_REAL
            VAR_INPUT
		         left:  REAL;
		         right:  REAL;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_GreaterThan_LREAL
            VAR_INPUT
		         left:  LREAL;
		         right:  LREAL;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_LessThan_INT
            VAR_INPUT
		         left:  INT;
		         right:  INT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_LessThan_SINT
            VAR_INPUT
		         left:  SINT;
		         right:  SINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_LessThan_DINT
            VAR_INPUT
		         left:  DINT;
		         right:  DINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_LessThan_LINT
            VAR_INPUT
		         left:  LINT;
		         right:  LINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_LessThan_USINT
            VAR_INPUT
		         left:  USINT;
		         right:  USINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_LessThan_UINT
            VAR_INPUT
		         left:  UINT;
		         right:  UINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_LessThan_UDINT
            VAR_INPUT
		         left:  UDINT;
		         right:  UDINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_LessThan_ULINT
            VAR_INPUT
		         left:  ULINT;
		         right:  ULINT;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_LessThan_REAL
            VAR_INPUT
		         left:  REAL;
		         right:  REAL;
	        END_VAR
            ;
    END_FUNCTION

            

    FUNCTION Assert_LessThan_LREAL
            VAR_INPUT
		         left:  LREAL;
		         right:  LREAL;
	        END_VAR
            ;
    END_FUNCTION

            